### ISSUE TITLE
Intermittent 502 error from serverless function

### ISSUE THREAD

**Issue by maxackerman** [stripe-samples/checkout-netlify-serverless#4]
Hi @thorsten-stripe & @jlengstorf thanks for this tutorial it was super helpful!

I used it as a starting point to get a site up and running, but I've noticed an issue where the "buy" button doesn't work sometimes. It looks like the serverless function is returning a 502 error, very intermittently.

I clicked around on the demo, and was able to replicate the problem there. It seems to happen after I've visited the checkout page and come back to the product page. But that might just be a coincidence. I had someone in another location confirm they are seeing the same issue.

Here is a screenshot of the error:
<img width="1136" alt="Screen Shot 2020-05-27 at 6 48 04 PM" src="https://user-images.githubusercontent.com/1308505/83080103-68d4f680-a04b-11ea-9f38-07a123be4239.png">

**Comment by jlengstorf** [comment]
hmm.. @thorsten-stripe that seems like we're sometimes not getting a valid response from the create-checkout function

I think it's this line throwing the above error:
https://github.com/stripe-samples/checkout-netlify-serverless/blob/master/public/index.html#L87

is this something you've seen before?

**Comment by thorsten-stripe** [comment]
I think this might be related to a known issue with lambda (when using a VPC network to connect your Lambda to other servers in the infrastructure it can prevent egress from Lambda to other hosts). In most cases we this can be resolved by setting `maxNetworkRetries: 2,`: https://github.com/thorwebdev/thorstickerstore/blob/master/functions/create-checkout.js#L7-L10 

I can open a PR for this tmr.
