### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by daryldauphin** [stripe-samples/checkout-netlify-serverless#8]
_**The error:**_

Error during invocation:  {
  errorMessage: "Cannot read property 'name' of undefined",
  errorType: 'TypeError'

After following the final video in the series on egghead.io, Im getting an error in the final netlify call. 

_**my code look slike this:**_

        name: product.name,
        description: product.description,
        images: [product.image],
        amount: product.amount,
        currency: product.currency,
        quantity: validatedQuantity,

**Comment by thorsten-stripe** [comment]
Heya, have you checked that you're importing your inventory correctly? https://github.com/stripe-samples/checkout-netlify-serverless/blob/master/functions/create-checkout.js#L20

What's the `console.log` for the `inventory`, `product`, and `sku` variables?

**Comment by daryldauphin** [comment]
![Screen Shot 2020-11-18 at 7 27 03 AM](https://user-images.githubusercontent.com/27041754/99530555-78d0f180-296f-11eb-92a2-a0bdcfc05899.png)

Yep, it seems that the inventory is correctly imported. Here is the full message i get.

**Comment by daryldauphin** [comment]
![Screen Shot 2020-11-18 at 7 59 57 AM](https://user-images.githubusercontent.com/27041754/99533553-18907e80-2974-11eb-8c45-fe9a25cd4cb5.png)


it looks like my inventory is being imported, for more reference here is more of the error

**Comment by thorsten-stripe** [comment]
Unfortunately this is not useful. Can you please `console.log` the following variables `inventory`, `product`, `quantity`, and `sku`?

**Comment by daryldauphin** [comment]
im a beginner, how would I go about doing the console.log on the variables?

**Comment by thorsten-stripe** [comment]
You can find some docs on it here: https://developer.mozilla.org/en-US/docs/Web/API/Console/log

In your `create-checkout.js` file, add the following code on line 28: https://github.com/stripe-samples/checkout-netlify-serverless/blob/master/functions/create-checkout.js#L28

```js
console.log(inventory, product, quantity, sku)
```

When the function runs you will then see the value of these variables logged to your terminal window.

**Comment by daryldauphin** [comment]
![Screen Shot 2020-11-19 at 5 16 06 PM](https://user-images.githubusercontent.com/27041754/99730790-06553400-2a8b-11eb-8f95-0cc95df5a71a.png)

Heres what I am receiving on my end so far, looks like when i console.logged, it did not output anything to the console. Maybe the file is not being ran.

**Comment by thorsten-stripe** [comment]
@daryldauphin it won't be logged to the browser but to your terminal. The same place you took the screenshot of the error above. In fact it should get logged just before the error itself.

**Comment by daryldauphin** [comment]
![Screen Shot 2020-11-19 at 8 39 38 PM](https://user-images.githubusercontent.com/27041754/99745290-59d57b00-2aa7-11eb-9d08-4124dd454431.png)

Here you go!

**Comment by thorsten-stripe** [comment]
Thanks, can you please paste the code of your `create-checkout.js` file here as well.

**Comment by daryldauphin** [comment]
const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const inventory = require('./data/products.json');

exports.handler = async (event) => {
  const { sku, quantity } = JSON.parse(event.body);
  const product = inventory.find((p) => p.sku === sku);
  const validatedQuantity = quantity > 0 && quantity < 11 ? quantity : 1;

  console.log(inventory, product, quantity, sku);



  const session = await stripe.checkout.sessions.create({
    payment_method_types: ['card'],
    billing_address_collection: 'auto',
    shipping_address_collection: {
      allowed_countries: ['US', 'CA'],
    },
    success_url: `${process.env.URL}/success.html`,
    cancel_url: process.env.URL,
    line_items: [
      {
        name: product.name,
        description: product.description,
        images: [product.image],
        amount: product.amount,
        currency: product.currency,
        quantity: validatedQuantity,
      },
    ],
  });

  return {
    statusCode: 200,
    body: JSON.stringify({
      sessionId: session.id,
      publishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
    }),
  };
};

**Comment by daryldauphin** [comment]
`const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);
const inventory = require('./data/products.json');

exports.handler = async (event) => {
  const { sku, quantity } = JSON.parse(event.body);
  const product = inventory.find((p) => p.sku === sku);
  const validatedQuantity = quantity > 0 && quantity < 11 ? quantity : 1;

  console.log(inventory, product, quantity, sku);



  const session = await stripe.checkout.sessions.create({
    payment_method_types: ['card'],
    billing_address_collection: 'auto',
    shipping_address_collection: {
      allowed_countries: ['US', 'CA'],
    },
    success_url: `${process.env.URL}/success.html`,
    cancel_url: process.env.URL,
    line_items: [
      {
        name: product.name,
        description: product.description,
        images: [product.image],
        amount: product.amount,
        currency: product.currency,
        quantity: validatedQuantity,
      },
    ],
  });

  return {
    statusCode: 200,
    body: JSON.stringify({
      sessionId: session.id,
      publishableKey: process.env.STRIPE_PUBLISHABLE_KEY,
    }),
  };
};`

**Comment by daryldauphin** [comment]
Any updates on the code? I was not able to debug it yet.

**Comment by thorsten-stripe** [comment]
@daryldauphin the function code looks fine, but it seems like your frontend code is not sending the sku ID correctly which is why the product is undefined. 

In your chrome dev tools, can you inspect the network request to the function in check that the sku parameter value is sent correctly?
![image](https://user-images.githubusercontent.com/23213994/99929153-1456cd80-2d87-11eb-8f10-36df123ee555.png)

**Comment by daryldauphin** [comment]
![Screen Shot 2020-11-23 at 8 02 13 AM](https://user-images.githubusercontent.com/27041754/99964997-338f3400-2d62-11eb-8e2b-3ac2beea9a68.png)
looks like its not pushing the sku

**Comment by thorsten-stripe** [comment]
Yes, that's the issue. Do you have your frontend code deployed somewhere? If you can point me to the URL for it I can have a look what's going wrong.

**Comment by daryldauphin** [comment]
https://5fbc63d11d2b3d13b5d2d40f--compassionate-galileo-e6fad7.netlify.app/

**Comment by thorsten-stripe** [comment]
Thanks, the problem is that the value for the hidden sku input is not correctly set:
![image](https://user-images.githubusercontent.com/23213994/100043103-ade5b400-2e47-11eb-94b9-f0645650caff.png)
It needs to be set within the value parameter.

The source of the issue is in your load-products.js file on line 9:
![image](https://user-images.githubusercontent.com/23213994/100043290-10d74b00-2e48-11eb-9db2-356227ef230c.png)
It needs to be `product.querySelector('[name=sku]').value = item.sku;`

**Comment by daryldauphin** [comment]
that fixed it! thank you!

**Comment by thorsten-stripe** [comment]
Great 👍
